version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "db"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: ${DATABASE_USERNAME:-task_user}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD:-taskPassW0rd}
      DATABASE_NAME: ${DATABASE_NAME:-task_db}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-task_db}
      POSTGRES_USER: ${POSTGRES_USER:-task_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-taskPassW0rd}
