version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      DB_HOST: "db"
      DB_PORT: "5432"
      DB_USERNAME: ${DB_USERNAME:-task_user}
      DB_PASSWORD: ${DB_PASSWORD:-taskPassW0rd}
      DB_NAME: ${DB_NAME:-task_db}
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME:-task_db}
      POSTGRES_USER: ${DB_USERNAME:-task_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-taskPassW0rd}
    ports:
      - "5432:5432"
